version: "3.6"

services:
  node1:
    container_name: node1
    image: quay.io/coreos/etcd:v3.5.9
    # volumes:
    #   - node1-data:/etcd-data
    ports:
      - "${ETCD1_PORT}:2379"
    expose:
      - 2379
      - 2380
    networks:
      cluster_net:
        ipv4_address: 172.16.238.100
    environment:
      - ETCDCTL_API=3
    command:
      - /usr/local/bin/etcd
      - --data-dir=/etcd-data
      - --name=node1
      - --initial-advertise-peer-urls=http://172.16.238.100:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://172.16.238.100:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-cluster=node1=http://172.16.238.100:2380,node2=http://172.16.238.101:2380,node3=http://172.16.238.102:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=docker-etcd
      - --auto-compaction-retention=1
      - --auto-compaction-mode=periodic

  node2:
    container_name: node2
    image: quay.io/coreos/etcd:v3.5.9
    # volumes:
    #   - node2-data:/etcd-data
    networks:
      cluster_net:
        ipv4_address: 172.16.238.101
    environment:
      - ETCDCTL_API=3
    ports:
      - "${ETCD2_PORT}:2379"
    expose:
      - 2379
      - 2380
    command:
      - /usr/local/bin/etcd
      - --data-dir=/etcd-data
      - --name=node2
      - --initial-advertise-peer-urls=http://172.16.238.101:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://172.16.238.101:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-cluster=node1=http://172.16.238.100:2380,node2=http://172.16.238.101:2380,node3=http://172.16.238.102:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=docker-etcd
      - --auto-compaction-retention=1
      - --auto-compaction-mode=periodic
  node3:
    container_name: node3
    image: quay.io/coreos/etcd:v3.5.9
    # volumes:
    #   - node3-data:/etcd-data
    networks:
      cluster_net:
        ipv4_address: 172.16.238.102
    environment:
      - ETCDCTL_API=3
    ports:
      - "${ETCD3_PORT}:2379"
    expose:
      - 2379
      - 2380
    command:
      - /usr/local/bin/etcd
      - --data-dir=/etcd-data
      - --name=node3
      - --initial-advertise-peer-urls=http://172.16.238.102:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://172.16.238.102:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-cluster=node1=http://172.16.238.100:2380,node2=http://172.16.238.101:2380,node3=http://172.16.238.102:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=docker-etcd
      - --auto-compaction-retention=1
      - --auto-compaction-mode=periodic
  backend1:
    container_name: backend1
    restart: unless-stopped
    build: backend
    command: bash -c "cd /AttackMonitor && pnpm install && node index.js"
    environment:
      - PORT=${PORT}
      - ETCD1_PORT=${ETCD1_PORT}
      - ETCD2_PORT=${ETCD2_PORT}
      - ETCD3_PORT=${ETCD3_PORT}
    ports:
      - 3001:${PORT}
  backend2:
    container_name: backend2
    restart: unless-stopped
    build: backend
    command: bash -c "cd /AttackMonitor && pnpm install && node index.js"
    environment:
      - PORT=${PORT}
      - ETCD1_PORT=${ETCD1_PORT}
      - ETCD2_PORT=${ETCD2_PORT}
      - ETCD3_PORT=${ETCD3_PORT}
    ports:
      - 3002:${PORT}
  backend3:
    container_name: backend3
    restart: unless-stopped
    build: backend
    command: bash -c "cd /AttackMonitor && pnpm install && node index.js"
    environment:
      - PORT=${PORT}
      - ETCD1_PORT=${ETCD1_PORT}
      - ETCD2_PORT=${ETCD2_PORT}
      - ETCD3_PORT=${ETCD3_PORT}
    ports:
      - 3003:${PORT}
# volumes:
#   node1-data:
#   node2-data:
#   node3-data:

networks:
  cluster_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
